
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - module.x-helm.dev
  resources:
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - module.x-helm.dev
  resources:
  - workflows/finalizers
  verbs:
  - update
- apiGroups:
  - module.x-helm.dev
  resources:
  - workflows/status
  verbs:
  - get
  - patch
  - update
